# Generated by Django 5.0.6 on 2024-05-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrm', '0004_auto_20200327_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AlterField(
            model_name='student1',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=10),
        ),
    ]
