# Generated by Django 5.0.6 on 2024-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrm', '0006_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='no_of_copies',
            field=models.CharField(default=42, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='subject',
            field=models.CharField(default=65, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=20),
        ),
    ]
